### PR TITLE
Support external SqlConnection and SqlTransaction.

### PR DESCRIPTION
**Pull request by jimmcslim**
SqlBulkCopy has a constructor that permits a SqlConnection and
SqlTransaction to be provided. Expose this to support applications where
the BulkWriter needs to run in the context of a transaction.

### CODE REVIEW

**Comment by jbogard** [comment]
Conflicts :(

**Comment by jimmcslim** [comment]
Ok, all good now.

I reverted the change I made in commit 5e47199 since it is outside the scope of the PR. Although I think there still is a bug re the handling of the `[NotMapped]` attribute?

**Comment by pedroreys** [comment]
I believe the issue with the `[NotMapped]` was fixed by https://github.com/HeadspringLabs/bulk-writer/pull/21

**Comment by jimmcslim** [comment]
Indeed. All looks good to go now @jbogard, a new release would be grand!

**Comment by ErikEJ** [comment]
Bring it on!

**Pull request merged**
